### ISSUE TITLE
Auth0 Login is not working with routing strategy { useHash: true } in Angular 12

### ISSUE THREAD

**Issue by vinodifour** [auth0/auth0-angular#189]
Hello, 

I am trying to integrate Auth0 Login with Microsoft Office Word Add-in, The issue i'm facing is, I've to use
HashLocationStrategy in order to make my routing work in add-in iframe. But it seems like the auth0 login is not working with given routing strategy as it constantly returning false to my 'IsAuthorized$' Observable.

Also, I've checked with given  [auth0-angular-samples-Sample-01](https://github.com/auth0-samples/auth0-angular-samples/tree/master/Sample-01) auth0 demo on git hub for browser angular application and it seem working fine, But when i tried to apply { useHash: true }  in my routing imports it prevents me from getting authenticated, So Please verify this issue and let us know if there any suggestion and  solution for the same.

For quick review of my demo code, here is the link: [Auth0 sample with HashLocationStrategy](https://ifourtechnolab-my.sharepoint.com/:f:/p/vimal/EkeISMygextIo8DU-TBJ7n8Ber1pkeJcbJc7VTvb50eYmg?e=SvskFk)

Any small help would be appreciated.
Thank you.

**Comment by frederikprijck** [comment]
Thanks for reporting this. I believe this is a bug in the SDK and will need some investigation.

**Comment by vinodifour** [comment]
> Thanks for reporting this. I believe this is a bug in the SDK and will need some investigation.

Thanks @frederikprijck  for your prompt reply. any ETA for fixing this? We need this fix to go to production.

**Comment by frederikprijck** [comment]
No ETA yet. I assume this isn't an easy fix, or at least it will need some good amount of debugging and testing eitherway.

Happy to review a PR if you can create one, that would definetly speed things up.

**Comment by frederikprijck** [comment]
I just merged a PR that solves this, I am planning to cut a release today or tomorrow which should include the fix for using useHash.

**Comment by purvibarot** [comment]
Hello @frederikprijck! 

Thank you for looking into the issue, but i'm not sure why do i still facing the same issue, 

Hash Routing is very important for us as we are working on Word Add-in.

Please find below link where i have posted by sample application which is not working with routing strategy { useHash: true }.

https://ifourtechnolab-my.sharepoint.com/:u:/p/vimal/EVK6qT9AELhHgMaSo8KfCUsBEMkCvKoK_BGGwNzAVVzx3g?e=AlcOsm

Its blocker for us as we cannot move further without this. 

Please let me know if you need any more details.

Regards,
Purvi

**Comment by frederikprijck** [comment]
@purvibarot ,

The linked sample uses `@auth0/auth0-angular` version **1.3.2**. The fix is released as part of version **1.6.2** (see https://github.com/auth0/auth0-angular/blob/master/CHANGELOG.md#v162-2021-09-15). Upgrading your application to use the latest `@auth0/auth0-angular` should make it work as expected.

**Comment by juventusjude** [comment]
I am having the same issue even with"@auth0/auth0-angular": "^1.11.1",
useHash  isauthenticated$ returning false and user$ returning false too.
